### ISSUE TITLE
click on shift schould show modal all possible shifts

### ISSUE THREAD

**Issue by jimbo-on-ruby** [jimbo-on-ruby/shift-planner-frontend#28]

**Comment by Elux91** [comment]
so far I can show all shift_types availabe and I created a service to update the shit.
I just have to implement the api call back to the server.

**Comment by Elux91** [comment]
I think if I move the open modal function to my departmenController it should work just fine. this will allow me to call the update function on the object that is bound to the UI

**Comment by Elux91** [comment]
updating a single cell is working.

###next step:

update multiple cells

###todo:

best solution would probably to add and directive to all shift  cells and on mousedown event it should change the background colour and save them somewhere.

**Comment by Elux91** [comment]
I will just add the indexes to the array on the first click and the follow-up mouseover.
this may lead to duplication. Updating the same cell multiple times, but I don't care.

**Comment by Elux91** [comment]
I can just save the shift id in a list before making the api call and and before making the next I check if the shift id is already part of the list.
